services:
  postgres:
    image: postgres:16.4
    container_name: almaz-postgres
    environment:
      POSTGRES_USER: almaz
      POSTGRES_PASSWORD: almazpassword
      POSTGRES_DB: almaz_db
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - '5434:5432'
